# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.22
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: We are using v7labs.com to OCR the image document so it can be processed
    in this module
repo_name: Tools to read the documents in pdf or image format to be imported to odoo
repo_slug: https://github.com/solusiaglis/sai-ocr
repo_website: https://github.com/OCA/https://github.com/solusiaglis/sai-ocr
use_pyproject_toml: true
use_ruff: true

